Fix devcheck for POSIX
Also refactor for readibility and simplicity

diff --git a/devcheck b/devcheck
--- a/devcheck
+++ b/devcheck
@@ -1,4 +1,5 @@
-#!/bin/sh
+#!/bin/bash
+
 # Copyright 2019 Google LLC
 #
 # Licensed under the Apache License, Version 2.0 (the "License");
@@ -15,9 +16,29 @@
 
 # This script runs all tests and examples and verifies they work as expected.
 
-[[ "${BASH_SOURCE[0]}" != "${0}" ]] && EXIT=return || EXIT=exit
+python3 -m unittest discover --start-directory . --pattern '*_test.py' --verbose
 
-python3 -m unittest discover -s . -p '*_test.py' -v || { RESULT=$? ; echo -e "\n\n Test failed with code $RESULT\n\n" ; $EXIT $RESULT ; }
+if [ $? -ne 0 ]; then
+  echo "Test failed with code $?"
+  exit
+fi
 
- eval $(find examples/ -name 'run.sh' -printf 'echo -e "\\n\\n+++++++++++ Running: %p" && %p && ') echo -e '+++++\\n\\nChecks: OK' || { RESULT=$? ; echo -e "+++++\n\nChecks: ERROR (status: $RESULT) above" ; $EXIT $RESULT ; }
+tests_passed=true
 
+for test_script in `find examples/ -type f -name run.sh`; do
+  test_directory="$( dirname "$test_script" )"
+  example_name="$( basename "$test_directory" )"
+  echo "Running $example_name"
+  if $test_script; then
+    echo "Checks: OK"
+  else
+    echo "Checks: ERROR (status: $?)"
+    tests_passed=false
+  fi
+done
+
+if [ "$tests_passed" = "true" ]; then
+  echo "Tests passed"
+else
+  echo "Tests failed"
+fi
