Update `tag_version` to reference `README.rst` now

diff --git a/tag_version b/tag_version
--- a/tag_version
+++ b/tag_version
@@ -33,13 +33,16 @@ if [ -n "${STATUS_OUTPUT}" ] ; then
 fi
 
 echo "Applying tag ${VER} ${MESSAGE}"
-sed -i -E "s/VERSION = '([.0-9]+)'/VERSION = '${VER}'/" sampletester/cli.py
-sed -i -E "s/Version: ([.0-9]+)/Version: ${VER}/" README.md
-sed -i -E "s/version='([.0-9]+)'/version='${VER}'/" setup.py
-sed -i -E "s/version = '([.0-9]+)'/version = '${VER}'/" docs/conf.py
-sed -i -E "s/release = '([.0-9]+)'/release = '${VER}'/" docs/conf.py
-git commit -m "Tagging ${VER}" -m "${MESSAGE}" sampletester/cli.py README.md setup.py docs/conf.py
-git tag -a "v${VER}" -m "${MESSAGE}"
+sed -i -E "s/VERSION = '([.0-9]+)'/VERSION = '${VER}'/" sampletester/cli.py && \
+sed -i -E "s/Version: ([.0-9]+)/Version: ${VER}/" README.rst && \
+sed -i -E "s/version='([.0-9]+)'/version='${VER}'/" setup.py && \
+sed -i -E "s/version = '([.0-9]+)'/version = '${VER}'/" docs/conf.py && \
+sed -i -E "s/release = '([.0-9]+)'/release = '${VER}'/" docs/conf.py && \
+git commit -m "Tagging ${VER}" -m "${MESSAGE}" sampletester/cli.py README.rst setup.py docs/conf.py && \
+git tag -a "v${VER}" -m "${MESSAGE}" && \
+echo "Finished applying tag ${VER}" && exit 0
 
-echo "Finished applying tag ${VER}"
+echo "Could not complete tagging process"
+exit 1
+
 
