Allow passing an arbitrary number of config yaml docs, and auto-detect their types (#105)
Now the user can pass an arbitrary number of glob expressions in the `sample-tester` command line. 

* If any of the globs resolve to directories, sample-tester searches for config YAML documents (testplans and manifests) only in the specified files and recursively in the specified directories.

* If none of the globs resolve to directories:
  * if the globs do not result in obtaining at least one testplan document, recursively search under the working directory for yaml files to extract testplan documents
  * if the globs do not result in obtaining at least one manifest document, recursively search under the working directory for yaml files to extract manifest documents

In all of the above, the type of the YAML docs extracted from each processed YAML file is determined:
* preferentially by the top-level `type` field (`manifest/.+` for manifests, `test/samples` for testplans)
* if not `type` field is present, for backward compatibility we use the filename from which the document was extracted: documents extracted from `*.manifest.yaml` files are classified as manifests, and those from other `*.yaml` files are classified as testplans)

This PR includes tests and documentation updates.

This fixes #52 (and goes beyond it as described above)

diff --git a/examples/convention-tag/test-convention-tag b/examples/convention-tag/test-convention-tag
--- a/examples/convention-tag/test-convention-tag
+++ b/examples/convention-tag/test-convention-tag
@@ -17,9 +17,29 @@
 # Exit correctly depending on whether this file is being sourced or executed.
 [[ "${BASH_SOURCE[0]}" != "${0}" ]] && EXIT=return || EXIT=exit
 
+output_file="$(mktemp /tmp/sample-tester.XXXXXXXXX )"
+
 pushd "$(dirname ${BASH_SOURCE})/../.." >& /dev/null
-sample-tester -v detailed ${FLAGS:---xunit=/tmp/xunit.tag.xml} examples/convention-tag/language.test.yaml examples/convention-tag/language.manifest.yaml
+sample-tester -v detailed ${FLAGS:---xunit=/tmp/xunit.tag.xml} examples/convention-tag/language.test.yaml examples/convention-tag/language.manifest.yaml >& $output_file 
 code=$?
+
+if [[ $code -eq 0 ]] ; then
+  for expected_text in                        \
+    'In setup'  \
+    'In teardown'  \
+    'Language samples test'  \
+    'A test defined via yaml directives'  \
+    "A test defined via 'code'" \
+    ;
+  do
+    if ! grep --silent "$expected_text" "$output_file"; then
+      echo "Assertion failed"
+      echo "Expected \`$expected_text\` in $output_file"
+      code=1
+      break
+    fi
+  done
+fi
 
 popd >& /dev/null
 ${EXIT} $code
